# spring
spring:
  profiles:
    active:
#    - pro
    - dev
#    - test
  thymeleaf:
    cache: false # 关闭缓存
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: NON_NULL
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true

# mybatis
#mybatis:
#  type-aliases-package: cn.com.sparknet.sjMessage.app.entity # 指定别名设置的包为所有entity
#  configuration:
#    map-underscore-to-camel-case: true # 驼峰命名规范
#  mapper-locations: # mapper映射文件位置
#    - classpath:mapping/**/*Mapper.xml

# mybatis - plus
mybatis-plus:
  mapper-locations: classpath:mapping/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.com.sparknet.sjMessage.*.entity # 指定别名设置的包为所有entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
      db-type: oracle
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

# log
logging:
  config: classpath:logback-admin.xml
  level:
  - cn.com.sparknet.sjMessage.app.mapper: trace