# server port
server:
  port: 8081

# database
datasource:
  tns: (DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.1.149)(PORT = 1521)))(CONNECT_DATA =(SID = QT12)))
  tns_sid: 192.168.1.149:1521:QT12

# spring
spring:
  datasource:
    max-idle: 10
    max-wait: 10000
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      sj_message:
          url: jdbc:oracle:thin:@${datasource.tns_sid}
          username: sj_message
          password: sj_message
      oa01_nj:
        url: jdbc:oracle:thin:@${datasource.tns_sid}
        username: cityoa_new_nj
        password: cityoa_new_nj
      oa02_wx:
        url: jdbc:oracle:thin:@${datasource.tns_sid}
        username: cityoa_new_wx
        password: cityoa_new_wx
      oa03_xz:
          url: jdbc:oracle:thin:@${datasource.tns_sid}
          username: cityoa_new_xz
          password: cityoa_new_xz
      oa04_cz:
        url: jdbc:oracle:thin:@${datasource.tns_sid}
        username: cityoa_new_cz
        password: cityoa_new_cz
      oa05_sz:
        url: jdbc:oracle:thin:@${datasource.tns_sid}
        username: cityoa_new_sz
        password: cityoa_new_sz
      oa06_nt:
        url: jdbc:oracle:thin:@${datasource.tns_sid}
        username: cityoa_new_nt
        password: cityoa_new_nt
      oa07_lyg:
        url: jdbc:oracle:thin:@${datasource.tns_sid}
        username: cityoa_new_lyg
        password: cityoa_new_lyg
      oa08_ha:
        url: jdbc:oracle:thin:@${datasource.tns_sid}
        username: cityoa_new_ha
        password: cityoa_new_ha
      oa09_yc:
        url: jdbc:oracle:thin:@${datasource.tns_sid}
        username: cityoa_new_yc
        password: cityoa_new_yc
      oa10_yz:
        url: jdbc:oracle:thin:@${datasource.tns_sid}
        username: cityoa_new_yz
        password: cityoa_new_yz
      oa11_zj:
        url: jdbc:oracle:thin:@${datasource.tns_sid}
        username: cityoa_new_zj
        password: cityoa_new_zj
      oa12_tz:
        url: jdbc:oracle:thin:@${datasource.tns_sid}
        username: cityoa_new_tz
        password: cityoa_new_tz
      oa13_sq:
        url: jdbc:oracle:thin:@${datasource.tns_sid}
        username: cityoa_new_sq
        password: cityoa_new_sq
      sj:
        url: jdbc:oracle:thin:@${datasource.tns_sid}
        username: gsoa_new
        password: gsoa_new
      driver-class-name: oracle.jdbc.driver.OracleDriver
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开validation-query注释
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

##多数据源的配置，需要引用sjMessage-dynamic-datasource
#dynamic:
#  datasource:
#    oa01_nj:
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      url: jdbc:oracle:thin:@${datasource.tns_sid}
#      username: cityoa_new_tz
#      password: cityoa_new_tz
#    oa02_wx:
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      url: jdbc:oracle:thin:@${datasource.tns_sid}
#      username: cityoa_new_zj
#      password: cityoa_new_zj
#    oa:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://localhost:1433;DatabaseName=sjMessage
#      username: sa
#      password: 123456
#    oa:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/sjMessage
#      username: renren
#      password: 123456
