# spring
spring:
  profiles:
    active:
#    - pro
    - dev
#    - test
  thymeleaf:
    cache: false # 关闭缓存
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 500MB
  #配置redis
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
                    #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
                    #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
                    #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
                    #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: 300ms
        
#配置elasticsearch
  data:
    elasticsearch:
      repositories:
        enabled: true #是否持久化
      cluster-name: elk-application
      cluster-nodes: 192.168.1.154:9300
# mybatis
mybatis:
  type-aliases-package: cn.com.sparknet.sjMessage.app.entity # 指定别名设置的包为所有entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  mapper-locations: # mapper映射文件位置
    - classpath:mapping/**/*Mapper.xml

# log
logging:
  config: classpath:logback-api.xml
  level:
  - cn.com.sparknet.sjMessage.app.mapper: trace
  - io.swagger.models.parameters.AbstractSerializableParameter: error